### PR TITLE
Create python.py

### PR DESCRIPTION
**Pull request by kevalpattani**
Please add this is a new function to your repository

### CODE REVIEW

**Review by aadi-basal-06 — CHANGES_REQUESTED** [review]
okay

**Comment by kevalpattani** [comment]
Oh I have changed please elabo.!

**Comment by aadi-basal-06** [comment]
use f string

**Review by aadi-basal-06 — COMMENTED** [review]
i want mebins name

**Review by aadi-basal-06 — APPROVED** [review]

**Pull request merged**
